services: 

  limesurvey:
    image: adamzammit/limesurvey:session
    ports:
      - 127.0.0.1:8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: e/xa|m|ple
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
      LIMESURVEY_PHP_SESSION_SAVE_HANDLER: redis
      LIMESURVEY_PHP_SESSION_SAVE_PATH: tcp://redis:6379
      TZ: Europe/London
    volumes:
      - ./plugins:/var/www/html/plugins
      - ./upload:/var/www/html/upload
      - ./config:/var/www/html/application/config
      - ./sessions:/var/lime/sessions

  mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: e/xa|m|ple
    volumes:
       - ./mysql:/var/lib/mysql
 
  redis:
    image: redis:7
