version: '2'

services:

  limesurvey:
    image: acspri/limesurvey:3.28.16-lts
    build: .
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: ex/a|mple
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ex/a|mple

